spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      password: ENC(IWlMcJEScSAyqr9M5QcrIIvODwUhi5S+NGoDJVPfDnc=)
  mail:
    default-encoding:
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
sm:
  jwt:
    secret: ${JWT_SECRET_SALT}
    expiration: 1800
    issuer: BeszterceKK